//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StampOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graphic : ICloneable 
    {
        public Graphic() 
        {
            Position = "Left";
            Size = 100;
            Url = string.Empty;
        }

        public Graphic(OStamp stamp)
        {
            OStamp = stamp;
            Position = "Left";
            Size = 100;
            Url = string.Empty;
        }

        public int Id { get; set; }
        public string Position { get; set; }
        public string Url { get; set; }
        public int Size { get; set; }
    
        public virtual OStamp OStamp { get; set; }

        public object Clone( )
        {
            return this.MemberwiseClone();
        }
    }
}
