//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StampOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order :ICloneable
    {
        public int Id { get; set; }
        public int Quantity { get; set; }    
        public virtual OStamp OStamp { get; set; }

        public Order( )
        {}

        public Order(OStamp stamp, int quantity = 1 )
        {
            Quantity = quantity;
            OStamp = stamp;
        }

        public object Clone()
        {
            return this.MemberwiseClone();
        }
    }
}
