//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StampOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StampLine : ICloneable 
    {
        public StampLine()
        {}

        public StampLine(OStamp stamp, int lineNr)
        {
            OStamp = stamp;
            LineNr = lineNr;
            FontSize = 10;
            Font = "Calibri";
        }
    
        public int Id { get; set; }
        public int LineNr { get; set; }
        public string Text { get; set; }
        public bool Bold { get; set; }
        public bool Italic { get; set; }
        public string Font { get; set; }
        public int FontSize { get; set; }
        public bool Underlined { get; set; }
        public int OStampId { get; set; }
    
        public virtual OStamp OStamp { get; set; }

        public object Clone()
        {
            return new StampLine()
            {
                Id = this.Id,
                LineNr = this.LineNr,
                Text = this.Text,
                Bold = this.Bold,
                Italic = this.Italic,
                Font = this.Font,
                FontSize = this.FontSize,
                Underlined = this.Underlined,
                OStampId = this.OStampId
            };               
        }
    }
}
