//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StampOnline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StampContainer : DbContext, StampOnline.Models.IStampContainer
    {
        public StampContainer()
            : base("name=StampContainer")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<StampLine> StampLines { get; set; }
        public DbSet<Graphic> Graphics { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OStamp> OStamps { get; set; }


        public new void SaveChanges()
        {
            base.SaveChanges();
        }

        public DbEntityEntry<OStamp> Entry(OStamp ostamp)
        {
            return base.Entry(ostamp);
        }
    }
}
